### ISSUE TITLE
Does not work for video anymore

### ISSUE THREAD

**Issue by VGrondin** [supervisely-ecosystem/serve-segment-anything-model#9]
Hi, 

I watched the video tutorial https://www.youtube.com/watch?v=PQCdLCN7uCo on how to use segment anything with videos, but it does not predict any masks. I tried it on single image project and it works fine. The only difference I see is that now there is a point in the middle by default when drawing the bounding box using the smart tool, and in the video it's not there. 

Thanks!

**Comment by TheoLisin** [comment]
Hi, @VGrondin 

After you draw the bounding box using the smart tool, you should see the following message in the SAM application logs.
```
Info    2023.08.23 16:55:23    INFO:     172.24.0.2:44050 - "POST /smart_segmentation HTTP/1.1" 200 OK
```

If you don't, make sure you choose the right app for smart tool. 
<img width="241" alt="image" src="https://github.com/supervisely-ecosystem/serve-segment-anything-model/assets/87002239/2de376a6-aa80-49dc-a493-42ce69d1e9b7">

**Comment by VGrondin** [comment]
Hi @TheoLisin ,

After quite some time debugging, it turned out that Serve anything model + video does not work on Firefox (no idea why). I tried the exact same setup and it worked exactly like it did in the youtube tutorial. 

Thanks!
